### ISSUE TITLE
Reuse travis helper scripts in our analyzers

### ISSUE THREAD

**Issue by carlosms** [src-d/lookout-sdk#16]
This project contains `_tools/install-lookout-latest.sh`, and both https://github.com/src-d/lookout-gometalint-analyzer and https://github.com/src-d/lookout-sonarcheck-analyzer have their own clone. Since this is a helper for Travis CI, it would make sense to have a unique common place for this. Probably it could live in this repo, and clone/wget it where needed.

**Comment by smacker** [comment]
Both analyzers are updated.
