### ISSUE TITLE
Feature request: request only changes for specific language(s)

### ISSUE THREAD

**Issue by smacker** [src-d/lookout-sdk#36]
Many analyzers can work only with some specific language or set of languages.
But receive all of them (including UAST parsing on lookoutd side and transferring huge payload).

**Comment by carlosms** [comment]
Makes sense to me. We'll need to discuss the needed `proto` changes before doing a PR. E.g. adding a single language or a list of languages, or adding an include and exclude list, etc.

**Comment by smacker** [comment]
We discussed offline to make this new field a list of languages.
