### ISSUE TITLE
Integration tests could also test lookout

### ISSUE THREAD

**Issue by dpordomingo** [src-d/lookout-sdk#51]
Since sdk is a `lookout` dependency, I wonder if it could be tested deeper here.
[Currently](https://github.com/src-d/lookout-sdk/blob/master/.travis.yml#L35), we only test the example analyzers with `lookout-sdk` binary (`lookout-tool`) what might be not enough.

We could try, for example, building `lookout-sdk` binary (`lookout-tool`) to ensure the sdk didn't break `lookout`.

**Comment by smacker** [comment]
Sorry @dpordomingo I just realized it's not going to work as is.

We lock lookout-sdk version in lookout. So building will always use locked version, not the one in PR.

Maybe we can work around it using some crazy `sed` or something else but I'm not sure it's a good idea.

**Comment by smacker** [comment]
@dpordomingo shall we close it?
