### ISSUE TITLE
README contains broken link to architecture.md

### ISSUE THREAD

**Issue by smola** [src-d/lookout-sdk#57]
https://github.com/src-d/lookout/blob/master/docs/architecture.md

**Comment by carlosms** [comment]
I believe this link is prepared for the changes in https://github.com/src-d/lookout/pull/398. @dpordomingo please confirm.

**Comment by dpordomingo** [comment]
yes :dancing_men:

**Comment by dpordomingo** [comment]
yes :dancing_men: (I didn't expect that much time till merging)
