### ISSUE TITLE
CI: Test go 1.11 and 1.10

### ISSUE THREAD

**Issue by carlosms** [src-d/lookout-sdk#6]
To follow our conventions we should test the latest two stable major versions of Go: https://github.com/src-d/guide/blob/master/engineering/conventions-go.md#supported-go-versions

I did a quick test and the travis matrix expansion does not work with the jobs/include scripts

> Each job included in jobs.include inherits the first value of the array that defines a matrix dimension.
https://docs.travis-ci.com/user/build-stages#build-stages-and-build-matrix-expansion

**Comment by se7entyse7en** [comment]
There's also an open [issue](https://github.com/travis-ci/travis-ci/issues/8295) requesting this feature.
