### ISSUE TITLE
Upgrade lookout and analyzers to lookout-sdk 0.6.1

### ISSUE THREAD

**Issue by carlosms** [src-d/lookout-sdk#84]
This is an umbrella issue to keep track of the upgrade to 0.6.1 in lookout and our analyzers.
- [x] https://github.com/src-d/lookout-test-fixtures/
- [x] lookout
  - [x] https://github.com/src-d/lookout/pull/598
  - [x] Tag a new release
- [x] https://github.com/src-d/lookout-gometalint-analyzer
  - [x] https://github.com/src-d/lookout-gometalint-analyzer/pull/31
  - [x] Tag a new release
- [x] https://github.com/src-d/lookout-sonarcheck-analyzer
  - [x] https://github.com/src-d/lookout-sonarcheck-analyzer/pull/25
  - [x] Tag a new release

**Comment by se7entyse7en** [comment]
Should we include lookout-sdk-ml?

**Comment by carlosms** [comment]
In my opinion, not for now. Let's discuss that in slack

**Comment by smacker** [comment]
I'll release analyzers after we have new lookout released (they get deployed automatically on release)

**Comment by carlosms** [comment]
Lookout [v0.10.0](https://github.com/src-d/lookout/releases/tag/v0.10.0) is out.

**Comment by smacker** [comment]
lookout-sonarcheck-analyzer tagged and successfully deployed.

**Comment by smacker** [comment]
lookout-gometalint-analyzer tagged and successfully deployed.
